### 회원가입 (매니저)
POST http://localhost:8080/api/signup/manager
Content-Type: application/json

{
  "email": "manager@gmail.com",
  "password": "12345",
  "phone": "010-1111-2222",
  "name": "매니저"
}

### 로그인 (매니저)
POST http://localhost:8080/api/signin/manager
Content-Type: application/json

{
  "email": "manager@gmail.com",
  "password": "12345"
}

### 회원 정보 조회 (매니저)
GET http://localhost:8080/api/partner/detail?id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQG1hbmFnZXIuY29tIiwianRpIjoiTENhazJFTCt4SWY5eHBCemxzcjBwNHp4di96Vnc4ZEFDVks2c3ZudTJHaz0iLCJyb2xlcyI6IlBBUlRORVIiLCJpYXQiOjE3MDc2NDU3NDcsImV4cCI6MTcwNzY0OTM0N30.rsXcgAWsj25zdpcGvjkOybaoBdOtE5hYU_u6oaG7IjM



### 매장 등록 (매니저)
POST http://localhost:8080/api/shop/partner/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsImp0aSI6IjJDdzFHVjlvTVpoNGNYb3R6bWUrT3kvbVluOHp1L1NlR2xUL0Q0M1gycW89Iiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA3NjY0MTgzLCJleHAiOjE3MDc2Njc3ODN9.zKwcw27yzWiXmsM34tcM63g1duBvaS7M89f6J2n1Pmg


{
  "location": "인천시 계양구",
  "managerId": 1,
  "shopName": "shop2",
  "phone": "032-1234-5670"
}

### 매장 수정 (매니저)
PUT http://localhost:8080/api/shop/partner/update/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsImp0aSI6IjJDdzFHVjlvTVpoNGNYb3R6bWUrT3kvbVluOHp1L1NlR2xUL0Q0M1gycW89Iiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA3NjY0MTgzLCJleHAiOjE3MDc2Njc3ODN9.zKwcw27yzWiXmsM34tcM63g1duBvaS7M89f6J2n1Pmg

{
  "managerId" : 1,
  "shopName": "shop1",
  "location": "서울시"
}

### 매장 삭제 (매니저)
DELETE http://localhost:8080/api/shop/partner/delete?id=1&shop=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsImp0aSI6IjJDdzFHVjlvTVpoNGNYb3R6bWUrT3kvbVluOHp1L1NlR2xUL0Q0M1gycW89Iiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA3NjY0MTgzLCJleHAiOjE3MDc2Njc3ODN9.zKwcw27yzWiXmsM34tcM63g1duBvaS7M89f6J2n1Pmg


### 매장 정보 (매니저)
GET http://localhost:8080/api/shop/partner/list?managerId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsImp0aSI6InNCeEVseXJjTXJtUkVqZ0xsZWtGTTVPTDh5SENUbzNCWGE5ZnF5VENQSXM9Iiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA3NjU4NTM0LCJleHAiOjE3MDc2NjIxMzR9.S3KCW8shoUzARXGPo6smUaK1UNref4RZreKXGZtTE5M


### 매장 예약 정보
GET http://localhost:8080/api/reservation/partner/reservation-list/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsImp0aSI6IjJDdzFHVjlvTVpoNGNYb3R6bWUrT3kvbVluOHp1L1NlR2xUL0Q0M1gycW89Iiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA3NjY0MTgzLCJleHAiOjE3MDc2Njc3ODN9.zKwcw27yzWiXmsM34tcM63g1duBvaS7M89f6J2n1Pmg


### 매장 예약 (대기 -> 승인)
PUT http://localhost:8080/api/reservation/partner/approval/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsImp0aSI6IjJDdzFHVjlvTVpoNGNYb3R6bWUrT3kvbVluOHp1L1NlR2xUL0Q0M1gycW89Iiwicm9sZXMiOiJQQVJUTkVSIiwiaWF0IjoxNzA3NjY0MTgzLCJleHAiOjE3MDc2Njc3ODN9.zKwcw27yzWiXmsM34tcM63g1duBvaS7M89f6J2n1Pmg

{
  "reservationStatus": "APPROVAL"
}

### 리뷰 삭제 (매니저)
DELETE http://localhost:8080/api/review/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYW5hZ2VyQG1hbmFnZXIuY29tIiwianRpIjoiTENhazJFTCt4SWY5eHBCemxzcjBwNHp4di96Vnc4ZEFDVks2c3ZudTJHaz0iLCJyb2xlcyI6IlBBUlRORVIiLCJpYXQiOjE3MDc2NDU3NDcsImV4cCI6MTcwNzY0OTM0N30.rsXcgAWsj25zdpcGvjkOybaoBdOtE5hYU_u6oaG7IjM
